### ISSUE TITLE
Why does python-barcode delete support for Python 3.5?

### ISSUE THREAD

**Issue by leafcoder** [WhyNotHugo/python-barcode#117]

**Comment by WhyNotHugo** [comment]
Python 3.5 is no longer supporter by the Python Foundation because it's past it's End Of Life.

Most libraries have dropped or will drop support for ancient versions of Python. You can use an older version of this library if you need to run and older python version.

Keep in mind that Python 3.5 itself is unmaintained and isn't even receiving security-related fixes.
