### ISSUE TITLE
So only generate barcode, can't read image to decode barcode ?

### ISSUE THREAD

**Issue by RicardoScofileld** [WhyNotHugo/python-barcode#15]

**Comment by jonemo** [comment]
Correct. 

For reading barcodes, your best options are 
* [zbarlight](https://pypi.org/project/zbarlight/) unless you are on Windows
* [pyzbar](https://pypi.org/project/pyzbar/) if you need Windows support
* [zxing](https://pypi.org/project/zxing/) if you want code that has been maintained since 2009 and have Java installed on your system
