### ISSUE TITLE
PyQt5 Compatibility

### ISSUE THREAD

**Issue by passananteg** [WhyNotHugo/python-barcode#156]
I'm making a barcode generator using PyQt5, I'm able to create the barcode in an SVG file, if I open the file with the explorer it looks perfect, but if I try to load it into a QSvgWidget it doesn't look ok! I tried different things, resizing and setting the properties of the writers but the barcode doesn't look ok! Any help?

![Screenshot_1](https://user-images.githubusercontent.com/44871512/170916562-df019b73-1ff4-4701-87ac-097f7d5396f3.png)

**Comment by WhyNotHugo** [comment]
You'll have better luck asking on Qt forums. I suggest including the SVG so they can point out anything unusual.

The SVGs generated by this library are pretty standard and don't have anything special that Qt would need to support, so I'm inclined to think it's a bug on their end (let me know if they claim otherwise).

**Comment by passananteg** [comment]
Hi @WhyNotHugo, I really appreciate the time that you took to answer! I thought the same thing, If a browser can show the barcode perfectly fine why is different in Qt! I will do that, I will make the question on Qt forums! Thank you!
