### ISSUE TITLE
Transparent ImageWriter background

### ISSUE THREAD

**Issue by Aculisme** [WhyNotHugo/python-barcode#64]
I love this library, and was wondering whether there were any plans for allowing transparent backgrounds as a option for the `background` attribute in `barcode.writer.ImageWriter`, effectively allowing for png barcodes with transparent backgrounds that are easy to paste over other images in PIL post-processing. This could be implemented by allowing for `rgba(r,g,b,a)` as an input instead of just `white`, `black`, `orange`, etc.:
```
options={
            "background":"rgba(0,0,0,0)",
            }
```
Thanks.

**Comment by tatarize** [comment]
That code actually is allowed as an input and works correctly. The only thing that would need to be changed is the initialization of the image mode to RGBA. Rather than RGB.
```python
class ImageWriterWithTransparency(ImageWriter):
    def _init(self, code):
        from PIL import Image, ImageDraw
        size = self.calculate_size(len(code[0]), len(code), self.dpi)
        self._image = Image.new("RGBA", size, self.background)
        self._draw = ImageDraw.Draw(self._image)
```

Use that as a your ImageWriter and you'll get transparencies.

**Comment by WhyNotHugo** [comment]
I'm tempted to just change the default to `RGBA`.

Just have to double check it won't break any existing setup (I can't think of any though, since the default is still `white`).

**Comment by WhyNotHugo** [comment]
Won't change the default since that would break JPEG, bug adding a parameter to use RGBA.

**Comment by tatarize** [comment]
This issue was about writing the transparency so the images could be put over other images, not changing the default mode.

You'd actually just need to check at the end before writing to JPG and convert it to RGB at the last second.
`image = image.convert('RGB')`

Then you'd have the best of both worlds. Also, since the barcodes are actually 2 color, you could also save them out as 2 bit pngs either palette, or black&white, which would make them much smaller in size.
