### ISSUE TITLE
Cannot save as png after packaging into exe file

### ISSUE THREAD

**Issue by Yinjiafeng** [WhyNotHugo/python-barcode#69]
![微信截图_20200426105205](https://user-images.githubusercontent.com/60877121/80309750-6f344080-8809-11ea-8828-0116bd39397a.png)
```
Traceback (most recent call last):
  File "site-packages\PIL\ImageFont.py", line 186, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 9: ordinal not in range(128)
```
This error occurs under python3.6, how to solve it

**Comment by WhyNotHugo** [comment]
What do you mean by "packing into exe file". This error gives me the impression that you haven't installed the library, what's the output of `pip freeze`?

**Comment by timgio** [comment]
im on this problem too.
im making barcode generator with your package, Tkinter, and wrap it using auto-py-to-exe
`import tkinter as tk
from tkinter import *
import barcode
from barcode.writer import ImageWriter

utama=tk.Tk()
utama.title("Generate barcode 128")
utama.geometry("350x250")

def clickOk():
    x=kode.get()
    bar1=barcode.get_barcode_class('code128')
    bar2=bar1(x,writer=ImageWriter())
    bar3=bar2.save('barcode')
    
kode=tk.Entry(utama)
kode.grid(row=0,column=0)
tombol=tk.Button(utama,text="OK",command=clickOk)
tombol.grid(row=1,column=0)

utama.mainloop()
`

work fine until i make it into .exe

**Comment by WhyNotHugo** [comment]
If the code works for regular Python, then there's nothing regarding this library at fault.

It looks like the issue is with the tool you're using to generate exe files, so you need to report the issue with them (it might also be that you're misusing it, I honestly have no idea). I've never developed on windows, so I've no idea about the extra complexities around it.

I don't have access to any Windows machines, so I can't really try it (nor do I have the time to research these tools, TBH).

**Comment by Phaugt** [comment]
found this: https://stackoverflow.com/questions/17620179/io-errorcannot-open-image-while-generating-barcode-after-freezing-using-py2exe

so apparently when changing to another font than the provided it works on windows.

so when i changed to: self.font_path = os.path.join(PATH, "fonts", "calibri.ttf") it works, so maybe the error is because we dont have that font as stanard on windows.

so when packaging to .exe alter the writer.py file to a font that is usable by the OS.
[your python installation directory]\Lib\site-packages\barcode\writer.py

**Comment by WhyNotHugo** [comment]
Can you extract you `exe` container and check if the font is in there?  
It's possible that the tool that creates the exe container isn't including the font inside of it. If that's the case, you should report that to them.

**Comment by Phaugt** [comment]
I checked in the dist folder (which PyInstaller creates) but I couldn't find any traces of the barcode-code but I guess it is a problem within PyInstaller. But for those who have the issue either have to include the .ttf file in their code or just swap to something that is recognized by PyInstaller (like in my case when I swapped to calibri since I use that in the gui). 

Hopefully it could help anyone that tries to make an .exe with your module.

**Comment by WhyNotHugo** [comment]
Keep in mind that patching `writer.py` with a different path is very brittle. Any update will undo those changes, and it'll be hard to track as time goes by.

I haven't used `PyInstaller`, so I can't provide much specific advice for it (I just use `pip` or the OS's package manager). I do suggest you report the issue to them though, it sounds like there's an issue packaging files when building these bundles.

The generated package / bundle _should_ contain, at least, these files:

```
barcode/fonts/DejaVuSansMono.ttf
barcode/writer.py
barcode/codex.py
barcode/itf.py
barcode/charsets/itf.py
barcode/charsets/code128.py
barcode/charsets/upc.py
barcode/charsets/code39.py
barcode/charsets/ean.py
barcode/charsets/__init__.py
barcode/errors.py
barcode/upc.py
barcode/isxn.py
barcode/base.py
barcode/pybarcode.py
barcode/version.py
barcode/ean.py
barcode/__init__.py
```

**Comment by Phaugt** [comment]
After reading some PyInstaller compiles the module (if I got that right) to a .pyc or .pyd file and somehow uses that in the .exe but that also means that the font file should be there somewhere, but then PyInstaller could have some trouble reading that I guess.

Here is a PyInstaller dist folder with only PyInstaller and barcode in the venv.

<img width="264" alt="barcode" src="https://user-images.githubusercontent.com/41962737/102390280-814f3300-3fd4-11eb-937b-264e8e041123.png">

So I guess that the module is somewhere.

**Comment by WhyNotHugo** [comment]
I'd expect to see all the files form this module there too. Maybe inside `Include`?  
I've no idea what `pyd` is though, I've never seen that before.

**Comment by zdposter** [comment]
I have the same error with pyinstaller and I was able to solve with adding following lines to `spec` file:

```py
added_files = [
         ("C:\\Program Files\\Python38\\Lib\\site-packages\\barcode\\fonts", 'barcode/fonts'),
         ]
a = Analysis(['b_test.py'],
             pathex=['C:\\test'],
             binaries=[],
             datas=added_files,
...
```

Anyway I would suggest to:
1.  allow to use custom font instead of hardcode (it should be easier that multiplatform detection of available monospace font ;-))
2.  provide better error message. e.g. replace [`font = ImageFont.truetype(self.font_path, self.font_size * 2)`](https://github.com/WhyNotHugo/python-barcode/blob/8fa7b0c23dfe2c5184b6c0cfd773aeec2cf6c707/barcode/writer.py#L434) with:
```
            try:
                font = ImageFont.truetype(self.font_path, self.font_size * 2)
            except IOError as error:
                print("Cannot open font:", self.font_path)
                raise error
```
