### ISSUE TITLE
Installation on Windows fails

### ISSUE THREAD

**Issue by josephernest** [WhyNotHugo/python-barcode#9]
On Windows 7 x64, Python 2.7 64-bit, 

    pip install python-barcode

gives

      Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\blah\appdata\local\temp\pip-build-q_pfeu\python-barcode\se
      tup.py", line 18, in <module>
      long_description=Path('README.rst').read_text(),
      AttributeError: 'WindowsPath' object has no attribute 'read_text'

Would you have any idea?

Thank you in advance.

**Comment by WhyNotHugo** [comment]
We don't really support Python 2. A few people have mentioned it worked for them, but it's not something that I can really support.

FWIW, I don't really have access to any windows machines, nor have I ever used Python on windows, so I can't really debug this at all (otherwise I wouldn't mind a quick look to figure out what's wrong).

I'd recommend you try with Python 3.6.

**Comment by WhyNotHugo** [comment]
@josephernest Any update, maybe on Python 3.6?

**Comment by WhyNotHugo** [comment]
Python3 has been reported to be working on Windows.
